### ISSUE TITLE
How to define the theme to use

### ISSUE THREAD

**Issue by AndreasZaschka** [alkacon/mercury-template#1]
## How to define the theme ?

As documented in the [README](https://github.com/alkacon/mercury-template#customizing-mercurys-css) the Mercury theme ship's with two themes
-  theme-blue
-  theme-red

As it seems to me, the **red theme is the default active theme**, but how to edit OpenCms to use for example the blue one ?

**Comment by arrowwind** [comment]
Explorer the html.  At the property editor there is a property called mercury.template. Change it to blue.

**Comment by aKandzior** [comment]
Out of office reply





Out of office reply - Abwesenheitsnotiz

I am currently out of office and will return October 28.


While I am out of office I have no access to my email.


In urgent cases, please contact Mrs. Martina Alger 
(m.alger@alkacon.com).

Ich bin zurzeit im Urlaub und werde am 28. Oktober wieder im Büro sein.


Während ich nicht im Büro bin habe ich keinen Zugriff auf meine Emails. 


Bitte wenden Sie sich in dringenden Fällen an Frau Martina Alger 
(m.alger@alkacon.com).

Kind regards - Mit freundlichen Grüßen,
Alexander Kandzior




Alkacon Software - The OpenCms Experts
An der Wachsfabrik 13
50996 Koeln, DE

http://www.alkacon.com
http://www.opencms.org

Alkacon Software GmbH & Co. KG
Amtsgericht Köln, HRA 32185, USt-IdNr.: DE259882372
Vertreten durch: Alkacon Verwaltungs GmbH
Geschäftsführer: Alexander Kandzior, Amtsgericht Köln, HRB 88218

**Comment by AndreasZaschka** [comment]
> Explorer the html. At the property editor there is a property called mercury.template. Change it to blue.

perfect 👍
